import {IPlayerMMRResponse} from '../../types/valapidocs.techchrism.me/PVP_ENDPOINTS/PlayerMMR.ts';

export const tempPlayerMMR: IPlayerMMRResponse = {
    Version: 1714061445946,
    Subject: '92fc5f4b-de99-596c-9122-875625c115b4',
    NewPlayerExperienceFinished: true,
    QueueSkills: {
        competitive: {
            TotalGamesNeededForRating: 0,
            TotalGamesNeededForLeaderboard: 0,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '03dfd004-45d4-ebfd-ab0a-948ce780dac4': {
                    SeasonID: '03dfd004-45d4-ebfd-ab0a-948ce780dac4',
                    NumberOfWins: 44,
                    NumberOfWinsWithPlacements: 44,
                    NumberOfGames: 83,
                    Rank: 22,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 22,
                    RankedRating: 0,
                    WinsByTier: {
                        '19': 6,
                        '20': 11,
                        '21': 22,
                        '22': 5,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 40,
                    NumberOfWinsWithPlacements: 43,
                    NumberOfGames: 98,
                    Rank: 20,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 19,
                    RankedRating: 5,
                    WinsByTier: {
                        '0': 3,
                        '17': 5,
                        '18': 10,
                        '19': 14,
                        '20': 11,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '22d10d66-4d2a-a340-6c54-408c7bd53807': {
                    SeasonID: '22d10d66-4d2a-a340-6c54-408c7bd53807',
                    NumberOfWins: 4,
                    NumberOfWinsWithPlacements: 4,
                    NumberOfGames: 13,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 19,
                    RankedRating: 0,
                    WinsByTier: {
                        '19': 4,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 5,
                },
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 36,
                    NumberOfWinsWithPlacements: 36,
                    NumberOfGames: 65,
                    Rank: 21,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 21,
                    RankedRating: 47,
                    WinsByTier: {
                        '19': 14,
                        '20': 19,
                        '21': 3,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '34093c29-4306-43de-452f-3f944bde22be': {
                    SeasonID: '34093c29-4306-43de-452f-3f944bde22be',
                    NumberOfWins: 49,
                    NumberOfWinsWithPlacements: 49,
                    NumberOfGames: 84,
                    Rank: 19,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 19,
                    RankedRating: 47,
                    WinsByTier: {
                        '13': 2,
                        '14': 7,
                        '15': 8,
                        '16': 4,
                        '17': 12,
                        '18': 12,
                        '19': 4,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1': {
                    SeasonID: '4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1',
                    NumberOfWins: 12,
                    NumberOfWinsWithPlacements: 12,
                    NumberOfGames: 24,
                    Rank: 22,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 22,
                    RankedRating: 15,
                    WinsByTier: {
                        '21': 9,
                        '22': 3,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6': {
                    SeasonID: '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6',
                    NumberOfWins: 1,
                    NumberOfWinsWithPlacements: 2,
                    NumberOfGames: 6,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 12,
                    RankedRating: 36,
                    WinsByTier: {
                        '0': 1,
                        '12': 1,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 8,
                },
                '9c91a445-4f78-1baa-a3ea-8f8aadf4914d': {
                    SeasonID: '9c91a445-4f78-1baa-a3ea-8f8aadf4914d',
                    NumberOfWins: 4,
                    NumberOfWinsWithPlacements: 7,
                    NumberOfGames: 13,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 13,
                    RankedRating: 34,
                    WinsByTier: {
                        '0': 3,
                        '11': 2,
                        '13': 2,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 5,
                },
                'aca29595-40e4-01f5-3f35-b1b3d304c96e': {
                    SeasonID: 'aca29595-40e4-01f5-3f35-b1b3d304c96e',
                    NumberOfWins: 7,
                    NumberOfWinsWithPlacements: 7,
                    NumberOfGames: 16,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 12,
                    RankedRating: 87,
                    WinsByTier: {
                        '12': 7,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 2,
                },
                'ec876e6c-43e8-fa63-ffc1-2e8d4db25525': {
                    SeasonID: 'ec876e6c-43e8-fa63-ffc1-2e8d4db25525',
                    NumberOfWins: 15,
                    NumberOfWinsWithPlacements: 16,
                    NumberOfGames: 39,
                    Rank: 19,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 19,
                    RankedRating: 58,
                    WinsByTier: {
                        '0': 1,
                        '18': 9,
                        '19': 6,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
            },
        },
        deathmatch: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 36,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '03dfd004-45d4-ebfd-ab0a-948ce780dac4': {
                    SeasonID: '03dfd004-45d4-ebfd-ab0a-948ce780dac4',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 3,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '34093c29-4306-43de-452f-3f944bde22be': {
                    SeasonID: '34093c29-4306-43de-452f-3f944bde22be',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 3,
                    NumberOfGames: 7,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 3,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6': {
                    SeasonID: '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                'ec876e6c-43e8-fa63-ffc1-2e8d4db25525': {
                    SeasonID: 'ec876e6c-43e8-fa63-ffc1-2e8d4db25525',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 2,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
            },
        },
        ggteam: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 43,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 1,
                    NumberOfGames: 2,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 1,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 3,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6': {
                    SeasonID: '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '9c91a445-4f78-1baa-a3ea-8f8aadf4914d': {
                    SeasonID: '9c91a445-4f78-1baa-a3ea-8f8aadf4914d',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 1,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 1,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
            },
        },
        hurm: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 0,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '03dfd004-45d4-ebfd-ab0a-948ce780dac4': {
                    SeasonID: '03dfd004-45d4-ebfd-ab0a-948ce780dac4',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 4,
                    NumberOfGames: 10,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 4,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 31,
                    NumberOfGames: 61,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 31,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
            },
        },
        newmap: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 42,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '03dfd004-45d4-ebfd-ab0a-948ce780dac4': {
                    SeasonID: '03dfd004-45d4-ebfd-ab0a-948ce780dac4',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 4,
                    NumberOfGames: 7,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 4,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '9c91a445-4f78-1baa-a3ea-8f8aadf4914d': {
                    SeasonID: '9c91a445-4f78-1baa-a3ea-8f8aadf4914d',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
            },
        },
        premier: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 39,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '03dfd004-45d4-ebfd-ab0a-948ce780dac4': {
                    SeasonID: '03dfd004-45d4-ebfd-ab0a-948ce780dac4',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 3,
                    NumberOfGames: 8,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 3,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 3,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
            },
        },
        seeding: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 49,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '573f53ac-41a5-3a7d-d9ce-d6a6298e5704': {
                    SeasonID: '573f53ac-41a5-3a7d-d9ce-d6a6298e5704',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
            },
        },
        spikerush: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 0,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 0,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: null,
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 0,
                },
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 22,
                    NumberOfGames: 47,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 22,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '34093c29-4306-43de-452f-3f944bde22be': {
                    SeasonID: '34093c29-4306-43de-452f-3f944bde22be',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 16,
                    NumberOfGames: 34,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 16,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '573f53ac-41a5-3a7d-d9ce-d6a6298e5704': {
                    SeasonID: '573f53ac-41a5-3a7d-d9ce-d6a6298e5704',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 2,
                    NumberOfGames: 2,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 2,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6': {
                    SeasonID: '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 49,
                    NumberOfGames: 90,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 49,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '9c91a445-4f78-1baa-a3ea-8f8aadf4914d': {
                    SeasonID: '9c91a445-4f78-1baa-a3ea-8f8aadf4914d',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 1,
                    NumberOfGames: 1,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 1,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                'aca29595-40e4-01f5-3f35-b1b3d304c96e': {
                    SeasonID: 'aca29595-40e4-01f5-3f35-b1b3d304c96e',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 29,
                    NumberOfGames: 63,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 29,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
            },
        },
        swiftplay: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 0,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '0981a882-4e7d-371a-70c4-c3b4f46c504a': {
                    SeasonID: '0981a882-4e7d-371a-70c4-c3b4f46c504a',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 2,
                    NumberOfGames: 6,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 2,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 11,
                    NumberOfGames: 25,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 11,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '34093c29-4306-43de-452f-3f944bde22be': {
                    SeasonID: '34093c29-4306-43de-452f-3f944bde22be',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 16,
                    NumberOfGames: 37,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 16,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '9c91a445-4f78-1baa-a3ea-8f8aadf4914d': {
                    SeasonID: '9c91a445-4f78-1baa-a3ea-8f8aadf4914d',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 23,
                    NumberOfGames: 49,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 23,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                'aca29595-40e4-01f5-3f35-b1b3d304c96e': {
                    SeasonID: 'aca29595-40e4-01f5-3f35-b1b3d304c96e',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 6,
                    NumberOfGames: 15,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 6,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
            },
        },
        unrated: {
            TotalGamesNeededForRating: 5,
            TotalGamesNeededForLeaderboard: 0,
            CurrentSeasonGamesNeededForRating: 1,
            SeasonalInfoBySeasonID: {
                '2de5423b-4aad-02ad-8d9b-c0a931958861': {
                    SeasonID: '2de5423b-4aad-02ad-8d9b-c0a931958861',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 3,
                    NumberOfGames: 5,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 3,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '34093c29-4306-43de-452f-3f944bde22be': {
                    SeasonID: '34093c29-4306-43de-452f-3f944bde22be',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 1,
                    NumberOfGames: 2,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 1,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '573f53ac-41a5-3a7d-d9ce-d6a6298e5704': {
                    SeasonID: '573f53ac-41a5-3a7d-d9ce-d6a6298e5704',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 2,
                    NumberOfGames: 2,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 2,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6': {
                    SeasonID: '7a85de9a-4032-61a9-61d8-f4aa2b4a84b6',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 41,
                    NumberOfGames: 66,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 41,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
                'aca29595-40e4-01f5-3f35-b1b3d304c96e': {
                    SeasonID: 'aca29595-40e4-01f5-3f35-b1b3d304c96e',
                    NumberOfWins: 0,
                    NumberOfWinsWithPlacements: 6,
                    NumberOfGames: 13,
                    Rank: 0,
                    CapstoneWins: 0,
                    LeaderboardRank: 0,
                    CompetitiveTier: 0,
                    RankedRating: 0,
                    WinsByTier: {
                        '0': 6,
                    },
                    GamesNeededForRating: 0,
                    TotalWinsNeededForRank: 9,
                },
            },
        },
    },
    LatestCompetitiveUpdate: {
        MatchID: '3bb3f6eb-c621-4b5f-b453-e11421c01b06',
        MapID: '/Game/Maps/Juliett/Juliett',
        SeasonID: '22d10d66-4d2a-a340-6c54-408c7bd53807',
        MatchStartTime: 1714059008868,
        TierAfterUpdate: 19,
        TierBeforeUpdate: 19,
        RankedRatingAfterUpdate: 0,
        RankedRatingBeforeUpdate: 6,
        RankedRatingEarned: -13,
        RankedRatingPerformanceBonus: 0,
        CompetitiveMovement: 'MOVEMENT_UNKNOWN',
        AFKPenalty: 0,
    },
    IsLeaderboardAnonymized: false,
    IsActRankBadgeHidden: false,
    OnboardingStatus: 'OnboardingComplete',
};
